name: Docker

on:
  workflow_call: 

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v2.5.0
      
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: marcoservio
        password: ${{ secrets.PASSWORD_DOCKER_HUB }}
  
    - name: Build and push Docker images
      uses: docker/build-push-action@v4.0.0
      with:       
        context: .
        file: ./Dockerfile     
        push: true       
        tags: marcoservio/go_ci:${{ github.ref_name }}
